Picture test
AidChen0509/ReadItAgain pull request #36
Opened 2023-12-26 14:11 UTC by chingshow

上傳圖片
1. 創建書本時可以一次傳一堆
2. edit書本細節
3. upload更多圖片 名字序號會接續下去
4. 刪除特定圖片
5. 刪除整本書

${\color{lightblue}Finally \space Finished}$

2023-12-26 14:14 UTC, yunchien77 reviewed
done

2023-12-26 17:19 UTC, Bryanlin920616 requested changes
在測試新增book的時候我condition打9.9成新，然後就錯了，發現在是資料庫condition的欄位長度只有3個字元，可能有點太小了，感覺要大一些，其他測試過都沒問題了，讚讚

2023-12-26 17:19 UTC, Bryanlin920616 commented on backend/app/main.py
>      book_state = 'on sold'
Line#1351
typo: state should be 'on sale'

2023-12-27 02:17 UTC, Bryanlin920616 approved these changes
OK 可以merge了👍感謝🙏

2023-12-27 02:31 UTC, merged